cg:
  max_iter: 200
  stop_tol: 1e-5
  matrix_size: 51200  # 矩阵大小 (n x n)，当使用真实矩阵时会被覆盖
  matrix_name: None  # 矩阵名称，从 matrix_set.csv 中选择， rajat05 比较小，但不适用于cg，muu适用于cg，但比较大
  matrix_data_dir: ~/data/matrix  # 矩阵数据目录
  matrix_set_csv: matrix_set.csv  # 矩阵信息CSV文件

spmv:
  tilesize: 32
  precision_cost_table:
    fp64: 1.0
    fp32: 0.7
    tf32: 0.55
    fp16: 0.35
    bf16: 0.33
    fp8: 0.15

reward:
  type: weighted
  w1: 1.0  # 数值误差奖励权重
  w2: 5.0  # 计算成本奖励权重
  w3: 5.0 # 收敛性奖励权重

ppo:
  gamma: 0.99
  learning_rate: 3e-4
  n_epochs: 10
  batch_size: 64
  clip_range: 0.2
  value_coef: 0.5
  entropy_coef: 0.01
  gpu: 0  # 使用 GPU 0
  update_interval: 10

train:
  total_steps: 1000
  eval_interval: 1000
  save_interval: 1000
  log_interval: 1000
  num_envs: 1

env:
  normalize_state: true
  reward_at_each_iter: false  # 是否在每次CG迭代后发放奖励
